# Generated by Django 5.0.6 on 2024-06-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser_role_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), (' owner', ' Owner'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
